/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as MainMembersRouteImport } from './routes/_main/members'
import { Route as MainMenusRouteImport } from './routes/_main/menus'
import { Route as MainRolesRouteRouteImport } from './routes/_main/roles/route'
import { Route as MainMembersMemberIdRouteImport } from './routes/_main/members.$memberId'
import { Route as MainRolesIndexRouteImport } from './routes/_main/roles/index'
import { Route as MainRolesRoleIdRouteImport } from './routes/_main/roles/$roleId'
import { Route as MainSmsChannelsRouteImport } from './routes/_main/sms/channels'
import { Route as MainSmsConfigRouteImport } from './routes/_main/sms/config'
import { Route as MainSmsRecordsRouteImport } from './routes/_main/sms/records'
import { Route as MainSmsTemplatesRouteImport } from './routes/_main/sms/templates'
import { Route as MainStorageChannelsRouteImport } from './routes/_main/storage/channels'
import { Route as MainStorageRecordsRouteImport } from './routes/_main/storage/records'
import { Route as MainStorageZonesRouteImport } from './routes/_main/storage/zones'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRoute,
} as any)
const MainMembersRoute = MainMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => MainRoute,
} as any)
const MainMenusRoute = MainMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => MainRoute,
} as any)
const MainRolesRouteRoute = MainRolesRouteRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => MainRoute,
} as any)
const MainMembersMemberIdRoute = MainMembersMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => MainMembersRoute,
} as any)
const MainRolesIndexRoute = MainRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRolesRouteRoute,
} as any)
const MainRolesRoleIdRoute = MainRolesRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => MainRolesRouteRoute,
} as any)
const MainSmsChannelsRoute = MainSmsChannelsRouteImport.update({
  id: '/sms/channels',
  path: '/sms/channels',
  getParentRoute: () => MainRoute,
} as any)
const MainSmsConfigRoute = MainSmsConfigRouteImport.update({
  id: '/sms/config',
  path: '/sms/config',
  getParentRoute: () => MainRoute,
} as any)
const MainSmsRecordsRoute = MainSmsRecordsRouteImport.update({
  id: '/sms/records',
  path: '/sms/records',
  getParentRoute: () => MainRoute,
} as any)
const MainSmsTemplatesRoute = MainSmsTemplatesRouteImport.update({
  id: '/sms/templates',
  path: '/sms/templates',
  getParentRoute: () => MainRoute,
} as any)
const MainStorageChannelsRoute = MainStorageChannelsRouteImport.update({
  id: '/storage/channels',
  path: '/storage/channels',
  getParentRoute: () => MainRoute,
} as any)
const MainStorageRecordsRoute = MainStorageRecordsRouteImport.update({
  id: '/storage/records',
  path: '/storage/records',
  getParentRoute: () => MainRoute,
} as any)
const MainStorageZonesRoute = MainStorageZonesRouteImport.update({
  id: '/storage/zones',
  path: '/storage/zones',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/login': typeof LoginRoute
  '/roles': typeof MainRolesRouteRouteWithChildren
  '/about': typeof MainAboutRoute
  '/members': typeof MainMembersRouteWithChildren
  '/menus': typeof MainMenusRoute
  '/members/$memberId': typeof MainMembersMemberIdRoute
  '/roles/$roleId': typeof MainRolesRoleIdRoute
  '/sms/channels': typeof MainSmsChannelsRoute
  '/sms/config': typeof MainSmsConfigRoute
  '/sms/records': typeof MainSmsRecordsRoute
  '/sms/templates': typeof MainSmsTemplatesRoute
  '/storage/channels': typeof MainStorageChannelsRoute
  '/storage/records': typeof MainStorageRecordsRoute
  '/storage/zones': typeof MainStorageZonesRoute
  '/roles/': typeof MainRolesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof MainAboutRoute
  '/members': typeof MainMembersRouteWithChildren
  '/menus': typeof MainMenusRoute
  '/': typeof MainIndexRoute
  '/members/$memberId': typeof MainMembersMemberIdRoute
  '/roles/$roleId': typeof MainRolesRoleIdRoute
  '/sms/channels': typeof MainSmsChannelsRoute
  '/sms/config': typeof MainSmsConfigRoute
  '/sms/records': typeof MainSmsRecordsRoute
  '/sms/templates': typeof MainSmsTemplatesRoute
  '/storage/channels': typeof MainStorageChannelsRoute
  '/storage/records': typeof MainStorageRecordsRoute
  '/storage/zones': typeof MainStorageZonesRoute
  '/roles': typeof MainRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/login': typeof LoginRoute
  '/_main/roles': typeof MainRolesRouteRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/members': typeof MainMembersRouteWithChildren
  '/_main/menus': typeof MainMenusRoute
  '/_main/': typeof MainIndexRoute
  '/_main/members/$memberId': typeof MainMembersMemberIdRoute
  '/_main/roles/$roleId': typeof MainRolesRoleIdRoute
  '/_main/sms/channels': typeof MainSmsChannelsRoute
  '/_main/sms/config': typeof MainSmsConfigRoute
  '/_main/sms/records': typeof MainSmsRecordsRoute
  '/_main/sms/templates': typeof MainSmsTemplatesRoute
  '/_main/storage/channels': typeof MainStorageChannelsRoute
  '/_main/storage/records': typeof MainStorageRecordsRoute
  '/_main/storage/zones': typeof MainStorageZonesRoute
  '/_main/roles/': typeof MainRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/roles'
    | '/about'
    | '/members'
    | '/menus'
    | '/members/$memberId'
    | '/roles/$roleId'
    | '/sms/channels'
    | '/sms/config'
    | '/sms/records'
    | '/sms/templates'
    | '/storage/channels'
    | '/storage/records'
    | '/storage/zones'
    | '/roles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/members'
    | '/menus'
    | '/'
    | '/members/$memberId'
    | '/roles/$roleId'
    | '/sms/channels'
    | '/sms/config'
    | '/sms/records'
    | '/sms/templates'
    | '/storage/channels'
    | '/storage/records'
    | '/storage/zones'
    | '/roles'
  id:
    | '__root__'
    | '/_main'
    | '/login'
    | '/_main/roles'
    | '/_main/about'
    | '/_main/members'
    | '/_main/menus'
    | '/_main/'
    | '/_main/members/$memberId'
    | '/_main/roles/$roleId'
    | '/_main/sms/channels'
    | '/_main/sms/config'
    | '/_main/sms/records'
    | '/_main/sms/templates'
    | '/_main/storage/channels'
    | '/_main/storage/records'
    | '/_main/storage/zones'
    | '/_main/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/members': {
      id: '/_main/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MainMembersRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/menus': {
      id: '/_main/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof MainMenusRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/roles': {
      id: '/_main/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof MainRolesRouteRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/members/$memberId': {
      id: '/_main/members/$memberId'
      path: '/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MainMembersMemberIdRouteImport
      parentRoute: typeof MainMembersRoute
    }
    '/_main/roles/': {
      id: '/_main/roles/'
      path: '/'
      fullPath: '/roles/'
      preLoaderRoute: typeof MainRolesIndexRouteImport
      parentRoute: typeof MainRolesRouteRoute
    }
    '/_main/roles/$roleId': {
      id: '/_main/roles/$roleId'
      path: '/$roleId'
      fullPath: '/roles/$roleId'
      preLoaderRoute: typeof MainRolesRoleIdRouteImport
      parentRoute: typeof MainRolesRouteRoute
    }
    '/_main/sms/channels': {
      id: '/_main/sms/channels'
      path: '/sms/channels'
      fullPath: '/sms/channels'
      preLoaderRoute: typeof MainSmsChannelsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/sms/config': {
      id: '/_main/sms/config'
      path: '/sms/config'
      fullPath: '/sms/config'
      preLoaderRoute: typeof MainSmsConfigRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/sms/records': {
      id: '/_main/sms/records'
      path: '/sms/records'
      fullPath: '/sms/records'
      preLoaderRoute: typeof MainSmsRecordsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/sms/templates': {
      id: '/_main/sms/templates'
      path: '/sms/templates'
      fullPath: '/sms/templates'
      preLoaderRoute: typeof MainSmsTemplatesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/storage/channels': {
      id: '/_main/storage/channels'
      path: '/storage/channels'
      fullPath: '/storage/channels'
      preLoaderRoute: typeof MainStorageChannelsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/storage/records': {
      id: '/_main/storage/records'
      path: '/storage/records'
      fullPath: '/storage/records'
      preLoaderRoute: typeof MainStorageRecordsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/storage/zones': {
      id: '/_main/storage/zones'
      path: '/storage/zones'
      fullPath: '/storage/zones'
      preLoaderRoute: typeof MainStorageZonesRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRolesRouteRouteChildren {
  MainRolesRoleIdRoute: typeof MainRolesRoleIdRoute
  MainRolesIndexRoute: typeof MainRolesIndexRoute
}

const MainRolesRouteRouteChildren: MainRolesRouteRouteChildren = {
  MainRolesRoleIdRoute: MainRolesRoleIdRoute,
  MainRolesIndexRoute: MainRolesIndexRoute,
}

const MainRolesRouteRouteWithChildren = MainRolesRouteRoute._addFileChildren(
  MainRolesRouteRouteChildren,
)

interface MainMembersRouteChildren {
  MainMembersMemberIdRoute: typeof MainMembersMemberIdRoute
}

const MainMembersRouteChildren: MainMembersRouteChildren = {
  MainMembersMemberIdRoute: MainMembersMemberIdRoute,
}

const MainMembersRouteWithChildren = MainMembersRoute._addFileChildren(
  MainMembersRouteChildren,
)

interface MainRouteChildren {
  MainRolesRouteRoute: typeof MainRolesRouteRouteWithChildren
  MainAboutRoute: typeof MainAboutRoute
  MainMembersRoute: typeof MainMembersRouteWithChildren
  MainMenusRoute: typeof MainMenusRoute
  MainIndexRoute: typeof MainIndexRoute
  MainSmsChannelsRoute: typeof MainSmsChannelsRoute
  MainSmsConfigRoute: typeof MainSmsConfigRoute
  MainSmsRecordsRoute: typeof MainSmsRecordsRoute
  MainSmsTemplatesRoute: typeof MainSmsTemplatesRoute
  MainStorageChannelsRoute: typeof MainStorageChannelsRoute
  MainStorageRecordsRoute: typeof MainStorageRecordsRoute
  MainStorageZonesRoute: typeof MainStorageZonesRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainRolesRouteRoute: MainRolesRouteRouteWithChildren,
  MainAboutRoute: MainAboutRoute,
  MainMembersRoute: MainMembersRouteWithChildren,
  MainMenusRoute: MainMenusRoute,
  MainIndexRoute: MainIndexRoute,
  MainSmsChannelsRoute: MainSmsChannelsRoute,
  MainSmsConfigRoute: MainSmsConfigRoute,
  MainSmsRecordsRoute: MainSmsRecordsRoute,
  MainSmsTemplatesRoute: MainSmsTemplatesRoute,
  MainStorageChannelsRoute: MainStorageChannelsRoute,
  MainStorageRecordsRoute: MainStorageRecordsRoute,
  MainStorageZonesRoute: MainStorageZonesRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
