/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as MainMenusRouteImport } from './routes/_main/menus'
import { Route as MainSmsChannelsRouteImport } from './routes/_main/sms/channels'
import { Route as MainSmsConfigRouteImport } from './routes/_main/sms/config'
import { Route as MainSmsRecordsRouteImport } from './routes/_main/sms/records'
import { Route as MainSmsTemplatesRouteImport } from './routes/_main/sms/templates'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRoute,
} as any)
const MainMenusRoute = MainMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => MainRoute,
} as any)
const MainSmsChannelsRoute = MainSmsChannelsRouteImport.update({
  id: '/sms/channels',
  path: '/sms/channels',
  getParentRoute: () => MainRoute,
} as any)
const MainSmsConfigRoute = MainSmsConfigRouteImport.update({
  id: '/sms/config',
  path: '/sms/config',
  getParentRoute: () => MainRoute,
} as any)
const MainSmsRecordsRoute = MainSmsRecordsRouteImport.update({
  id: '/sms/records',
  path: '/sms/records',
  getParentRoute: () => MainRoute,
} as any)
const MainSmsTemplatesRoute = MainSmsTemplatesRouteImport.update({
  id: '/sms/templates',
  path: '/sms/templates',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/login': typeof LoginRoute
  '/about': typeof MainAboutRoute
  '/menus': typeof MainMenusRoute
  '/sms/channels': typeof MainSmsChannelsRoute
  '/sms/config': typeof MainSmsConfigRoute
  '/sms/records': typeof MainSmsRecordsRoute
  '/sms/templates': typeof MainSmsTemplatesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof MainAboutRoute
  '/menus': typeof MainMenusRoute
  '/': typeof MainIndexRoute
  '/sms/channels': typeof MainSmsChannelsRoute
  '/sms/config': typeof MainSmsConfigRoute
  '/sms/records': typeof MainSmsRecordsRoute
  '/sms/templates': typeof MainSmsTemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/login': typeof LoginRoute
  '/_main/about': typeof MainAboutRoute
  '/_main/menus': typeof MainMenusRoute
  '/_main/': typeof MainIndexRoute
  '/_main/sms/channels': typeof MainSmsChannelsRoute
  '/_main/sms/config': typeof MainSmsConfigRoute
  '/_main/sms/records': typeof MainSmsRecordsRoute
  '/_main/sms/templates': typeof MainSmsTemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/menus'
    | '/sms/channels'
    | '/sms/config'
    | '/sms/records'
    | '/sms/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/menus'
    | '/'
    | '/sms/channels'
    | '/sms/config'
    | '/sms/records'
    | '/sms/templates'
  id:
    | '__root__'
    | '/_main'
    | '/login'
    | '/_main/about'
    | '/_main/menus'
    | '/_main/'
    | '/_main/sms/channels'
    | '/_main/sms/config'
    | '/_main/sms/records'
    | '/_main/sms/templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/menus': {
      id: '/_main/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof MainMenusRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/sms/channels': {
      id: '/_main/sms/channels'
      path: '/sms/channels'
      fullPath: '/sms/channels'
      preLoaderRoute: typeof MainSmsChannelsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/sms/config': {
      id: '/_main/sms/config'
      path: '/sms/config'
      fullPath: '/sms/config'
      preLoaderRoute: typeof MainSmsConfigRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/sms/records': {
      id: '/_main/sms/records'
      path: '/sms/records'
      fullPath: '/sms/records'
      preLoaderRoute: typeof MainSmsRecordsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/sms/templates': {
      id: '/_main/sms/templates'
      path: '/sms/templates'
      fullPath: '/sms/templates'
      preLoaderRoute: typeof MainSmsTemplatesRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainMenusRoute: typeof MainMenusRoute
  MainIndexRoute: typeof MainIndexRoute
  MainSmsChannelsRoute: typeof MainSmsChannelsRoute
  MainSmsConfigRoute: typeof MainSmsConfigRoute
  MainSmsRecordsRoute: typeof MainSmsRecordsRoute
  MainSmsTemplatesRoute: typeof MainSmsTemplatesRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainMenusRoute: MainMenusRoute,
  MainIndexRoute: MainIndexRoute,
  MainSmsChannelsRoute: MainSmsChannelsRoute,
  MainSmsConfigRoute: MainSmsConfigRoute,
  MainSmsRecordsRoute: MainSmsRecordsRoute,
  MainSmsTemplatesRoute: MainSmsTemplatesRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
